### ISSUE TITLE
`IndexError` when resuming from checkpoint

### ISSUE THREAD

**Issue by timothygebhard** [johannesulf/nautilus#31]
Hi! 🙂 

I have run into the following issue when trying to resume sampling from a checkpoint file:
```
Traceback (most recent call last):
  File "/lustre/home/tgebhard/projects/venv/scripts/nested_sampling/run_sampler.py", line 301, in <module>
    sampler.run(max_runtime=args.max_runtime, verbose=True)
  File "/lustre/home/tgebhard/projects/venv/fm4ar/nested_sampling/samplers.py", line 138, in run
    self.sampler.run(verbose=verbose)
  File "/home/tgebhard/.virtualenvs/venv/lib/python3.10/site-packages/nautilus/sampler.py", line 386, in run
    self.fill_bound(verbose=verbose)
  File "/home/tgebhard/.virtualenvs/venv/lib/python3.10/site-packages/nautilus/sampler.py", line 875, in fill_bound
    if len(self.blobs[-1]) > 0:
IndexError: list index out of range
```

Normally, resuming from a checkpoint has worked just fine for me, so I suspect that it might have to do with the fact that the last epoch before the checkpoint file was created "failed"?

```
Adding Bound 54
Adding Bound 54:     done
Ellipsoids:            32
Neural Networks:        4
Filling Bound 54:    done
N_like:            831800
N_eff:              28854
log Z:            -41.050
log V:            -41.003
f_live:             0.019

Adding Bound 55
Adding Bound 55:   failed
```

Perhaps it also has something to do with blobs (not) getting saved, which depends on the value of the `blobs_dtype` argument? (I am not explicitly passing any value for that at the moment — should I?)

Also, speaking of these failures, I gathered from the source code that this happens when the volume does not decrease after adding a new bound. What is the suggested way of handling this? It seems that sometimes just letting the code run and try again works, but I have also had cases where it would re-try and get stuck over again ~10 times before I eventually aborted the run. Should I just run again with more live points, or change the number of networks, or ...?

Thanks a lot in advance for any help with this! 🙌

**Comment by johannesulf** [comment]
Hi @timothygebhard! Thanks so much for filing the report, and sorry you encountered this issue. Could you send me the checkpoint file? Then I could see what's happening and hopefully fix that issue quickly.

Regarding your second question about adding new bounds "failing": your reading of the source code is entirely correct. The term "failed" is a bit misleading since it suggests something is wrong. It just indicates that nautilus is struggling a bit to learn the likelihood. I'll probably change it to "skipped" soon. In and of itself, it's not a problem. Nautilus will just sample further and see whether it can construct a better bound later with more data to learn from. If, as you describe, no new bound is added many times, this generally indicates that you probably profit from more live points.

**Comment by timothygebhard** [comment]
Thank you so much for your lightning-fast reply! ⚡  I have uploaded the problematic checkpoint file [here](https://timothygebhard.de/files/checkpoint.hdf5). Please let me know if you need anything else! 

Meanwhile, I will also start a new run with more live points to see if that reduces the number of "failures".

**Comment by johannesulf** [comment]
@timothygebhard Thanks so much for sending the file! I can verify the problem and I think I see exactly where it's coming from. I'll hopefully come up with a solution soon and merge it into main. I'll plan to make this part of the upcoming version 0.7.3.

**Comment by timothygebhard** [comment]
The `blobs` branch is looking very promising: I could indeed resume the run from the old checkpoint file! 🎉 

Regarding the likelihood: What I'm trying to do is estimate the posterior distribution for a set of parameters that describe a spectrum, that is, I run a (deterministic) simulator and compute the likelihood simply as `-0.5 * np.sum(((x_observed - x_simulated) / sigma) ** 2)`. The spectra have around 1000 wavelength bins. I have already managed to run it all at a lower resolution, and it's not like the posterior was anything crazy (i.e., it's all uni- or bimodal), but 4 or 5 parameters are poorly constrained, meaning the posterior basically matches the (uniform) prior. Additionally, the simulator might behave rather non-linearly for some parameters, which might also make it harder?

**Comment by johannesulf** [comment]
Thanks! I'll merge this into `main`.

And thanks for telling me some details about your problem. It seems like a fairly challenging likelihood. If the neural networks perfectly reproduce your likelihood, you should arrive at bound 54 with around 200,000 likelihood calls instead of 800,000. Similarly, that nautilus needs 32 ellipsoids to enclose the points also indicates that the distribution is highly non-Gaussian. But these numbers aren't entirely unreasonable. As always, check that your results are converged by running with different numbers of live points, and set `discard_exploration=True` for publication results.
