### ISSUE TITLE
Print some form of progress when verbose=False

### ISSUE THREAD

**Issue by jvines** [johannesulf/nautilus#36]
Hi,

I was wondering if it's possible for Nautilus to print some form of progress when verbose = False that isn't very invasive (such as dynesty's progress bar)? With verbose=True it fills the terminal and it's kind of annoying.

Of course this is not a high priority functionality, just a nice to have.

Thanks for this code btw, I'm eager to test it when fitting for exoplanets :)

**Comment by johannesulf** [comment]
Thanks for raising the issue and sorry for taking a bit longer to reply. Just to confirm: the issue is that the default output is too verbose, right? I think there should be an option to have no output. Similarly, the default output is very helpful since older information isn't removed. This helps trace nautilus' behavior. So the best option is to have some intermediate levels of verbosity, right?

**Comment by johannesulf** [comment]
I will have a shorter, more compact output implemented in the coming days. This should hopefully address this issue.
